language: cpp
os: osx

env:
    matrix:
        - ARCHITECTURE=i386
        - ARCHITECTURE=x86_64

matrix:
    fast_finish: true

install:
    - brew update
    - brew install clang-format

before_script:
    - clang-format -i $(git ls-files include/ src/*.hpp src/*.cpp)
    - git diff --exit-code

script:
    - mkdir build build/Debug build/Release

    - cd build/Debug
    - cmake ../.. -DCMAKE_OSX_ARCHITECTURES=$ARCHITECTURE -DCMAKE_BUILD_TYPE=Debug
    - cmake --build .
    - ctest --output-on-failure
    - cd ../..

    - cd build/Release
    - cmake ../.. -DCMAKE_OSX_ARCHITECTURES=$ARCHITECTURE -DCMAKE_BUILD_TYPE=Release
    - cmake --build .
    - ctest --output-on-failure
    - cd ../..
