language: cpp

branches:
  only:
    - master

matrix:
  fast_finish: true

  include:
    - os: osx
      env: ARCHITECTURE=x86_64 CMAKE_PREFIX_PATH=/usr/local/opt/qt5
    - os: osx
      env: ARCHITECTURE=i386
    - os: linux
      sudo: required
      dist: trusty

install:
  # - if [ ${TRAVIS_OS_NAME} == 'osx' ]; then brew update; fi
  # - if [ ${TRAVIS_OS_NAME} == 'osx' ]; then brew install clang-format; fi
  - if [ ${TRAVIS_OS_NAME} == 'osx' ] && [ ${ARCHITECTURE} == 'x86_64' ]; then brew update; fi
  - if [ ${TRAVIS_OS_NAME} == 'osx' ] && [ ${ARCHITECTURE} == 'x86_64' ]; then brew install qt5; fi

before_script:
  # - if [ ${TRAVIS_OS_NAME} == 'osx' ]; then clang-format -i $(git ls-files include/ src/*.hpp src/*.cpp); fi
  # - if [ ${TRAVIS_OS_NAME} == 'osx' ]; then git diff --exit-code; fi

script:
  - mkdir build
  - cd build

  - cmake .. -DCMAKE_OSX_ARCHITECTURES=$ARCHITECTURE -DCMAKE_BUILD_TYPE=Debug
  - cmake --build .
  - ctest --output-on-failure

  - cmake .. -DCMAKE_OSX_ARCHITECTURES=$ARCHITECTURE -DCMAKE_BUILD_TYPE=Release
  - cmake --build .
  - ctest --output-on-failure
