language: cpp

branches:
  only:
    - master

matrix:
  fast_finish: true

  include:
    - os: osx
      env: ARCHITECTURE=i386
    - os: osx
      env: ARCHITECTURE=x86_64

install:
  # - if [ ${TRAVIS_OS_NAME} == 'osx' ]; then brew update; fi
  # - if [ ${TRAVIS_OS_NAME} == 'osx' ]; then brew install clang-format; fi

before_script:
  # - if [ ${TRAVIS_OS_NAME} == 'osx' ]; then clang-format -i $(git ls-files include/ src/*.hpp src/*.cpp); fi
  # - if [ ${TRAVIS_OS_NAME} == 'osx' ]; then git diff --exit-code; fi

script:
  - mkdir build build/Debug build/Release

  - cd build/Debug
  - if [ ${TRAVIS_OS_NAME} == 'osx' ]; then cmake ../.. -DCMAKE_OSX_ARCHITECTURES=$ARCHITECTURE -DCMAKE_BUILD_TYPE=Debug; fi
  - cmake --build .
  - ctest --output-on-failure
  - cd ../..

  - cd build/Release
  - if [ ${TRAVIS_OS_NAME} == 'osx' ]; then cmake ../.. -DCMAKE_OSX_ARCHITECTURES=$ARCHITECTURE -DCMAKE_BUILD_TYPE=Release; fi
  - cmake --build .
  - ctest --output-on-failure
  - cd ../..
