language: cpp
os: osx

env:
    matrix:
        - ARCHITECTURE=i386
        - ARCHITECTURE=x86_64

matrix:
    fast_finish: true

install:
    - brew update
    - brew install clang-format

before_script:
    - clang-format -i $(git ls-files include/ src/*.hpp src/*.cpp)
    - git diff --exit-code

script:
    - mkdir build
    - cd build

    - cmake .. -DCMAKE_OSX_ARCHITECTURES=$ARCHITECTURE
    - cmake --build . --config Debug
    - cmake --build . --config Release

    - ctest --output-on-failure --build-config Debug
    - ctest --output-on-failure --build-config Release
