clone_depth: 50

branches:
  only:
    - master

environment:
  matrix:
    - CMAKE_GENERATOR: "Visual Studio 12 2013"
      CMAKE_PREFIX_PATH: C:/Qt/5.3/msvc2013_opengl
    - CMAKE_GENERATOR: "Visual Studio 12 2013 Win64"
      CMAKE_PREFIX_PATH: C:/Qt/5.3/msvc2013_64_opengl
    - CMAKE_GENERATOR: "Visual Studio 14 2015"
      CMAKE_PREFIX_PATH: C:/Qt/5.3/msvc2013_opengl
    - CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"
      CMAKE_PREFIX_PATH: C:/Qt/5.3/msvc2013_64_opengl

matrix:
  fast_finish: true

build_script:
  - mkdir build
  - cd build

  - cmake .. -G"%CMAKE_GENERATOR%"
  - cmake --build . --config Debug
  - cmake --build . --config Release

test_script:
  - ctest --output-on-failure --build-config Debug
  - ctest --output-on-failure --build-config Release
