clone_depth: 50

environment:
    matrix:
        - CMAKE_GENERATOR: "Visual Studio 12 2013"
        - CMAKE_GENERATOR: "Visual Studio 12 2013 Win64"

build_script:
    - mkdir build
    - cd build

    - cmake .. -G"%CMAKE_GENERATOR%"
    - cmake --build . --config Debug
    - cmake --build . --config Release

test_script:
    - ctest --output-on-failure --build-config Debug
    - ctest --output-on-failure --build-config Release
