clone_depth: 50

branches:
    only:
        - master

build_script:
    - mkdir build build\msvc2013_32 build\msvc2013_64

    - cd build\msvc2013_32
    - cmake ..\.. -G"Visual Studio 12 2013"
    - cmake --build . --config Debug
    - cmake --build . --config Release
    - cd ..\..

    - cd build\msvc2013_64
    - cmake ..\.. -G"Visual Studio 12 2013 Win64"
    - cmake --build . --config Debug
    - cmake --build . --config Release
    - cd ..\..

test_script:
    - cd build\msvc2013_32
    - ctest --output-on-failure --build-config Debug
    - ctest --output-on-failure --build-config Release
    - cd ..\..

    - cd build\msvc2013_64
    - ctest --output-on-failure --build-config Debug
    - ctest --output-on-failure --build-config Release
    - cd ..\..
